### ISSUE TITLE
Automation?

### ISSUE THREAD

**Issue by Tectors** [kem0x/Fortnite-Aes-Keys-Archive#15]
Why not automate the process for the new versions, instead of manually having to add them in when the version releases.
It's so easy and can be achievable using github actions and has a lot of benefits.

**Comment by AlexDev404** [comment]
That is a fact. I don't know why they don't do that.

**Comment by Tectors** [comment]
> That is a fact. I don't know why they don't do that.

I tried!
https://github.com/Tectors/Archive

And.. It works.
